[production]
porto-prod ansible_host=YOUR_PRODUCTION_HOST ansible_user=YOUR_SSH_USER

[staging]
porto-staging ansible_host=YOUR_STAGING_HOST ansible_user=YOUR_SSH_USER

[production:vars]
app_path=/home/dozernap/app

[staging:vars]
app_path=/home/dozernap/staging-app
